import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import Navbar from "@/components/navbar/Navbar";
import AuthProvider from "@/components/auth/AuthProvider";
import {ThemeProvider} from "@/components/context/ThemeContext";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Spontaneous",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider>
            <AuthProvider>
                <div className={'h-8 bg-black'}/>
                <Navbar/>
                <div className={'h-[1px]'} style={{'background': 'gray'}}/>
                {children}
                <Footer/>
            </AuthProvider>
        </ThemeProvider>
        </body>
        </html>
    );
}
